apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-fake-gpu-operator
  name: openshift-fake-gpu-operator-fakegpuconfig-viewer-role
rules:
- apiGroups:
  - gpu.openshift.io
  resources:
  - fakegpuconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpu.openshift.io
  resources:
  - fakegpuconfigs/status
  verbs:
  - get
